name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: build
        run: |
          npm ci
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build    
  DeployStaging:
    name: Deploy to Staging 
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://git-action-demo-dev.surge.sh'
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Deploy
        run:  |
          npm install --global surge
          surge --domain git-action-demo-dev.surge.sh --token ${{secrets.SURGE_TOKEN}}
        working-directory: build
            
  DeployProd:
    name: Deploy to Production 
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://git-action-demo.surge.sh'
    steps:
      - name: Deploy
        run:  |
          npm install --global surge
          ls
          surge --project build --domain git-action-demo.surge.sh --token ${{secrets.SURGE_TOKEN}}
