name: CI + CD

on: push

env:
  HTTP: https:// 
  FEATURE_DOMAIN: git-action-demo-${GITHUB_REF##*/}.surge.sh
  DEVELOPMENT_DOMAIN: git-action-demo-dev.surge.sh
  PRODUCTION_DOMAIN: git-action-demo.surge.sh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      
      - name: Run the tests
        run: npm run test
      
      - name: build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: simple-systems-artifect
          path: build  
    
  deploy-feature:
    name: Deploy to feature branch
    if: |
      contains( github.ref, 'feature' ) || contains( github.ref, 'bugfix' ) 
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'http://git-action-demo-${GITHUB_REF##*/}.surge.sh'
    steps:
      - name: get artifact
        uses: actions/download-artifact@v1
        with:
          name: simple-systems-artifect
      - name: deploy
        run: |
          npm install --global surge
          surge --project ./ --domain $FEATURE_DOMAIN --token ${{secrets.SURGE_TOKEN}}
        working-directory: simple-systems-artifect
  
  deploy-staging:
    name: Deploy to staging
    if: |
      github.event.ref == 'refs/heads/develop' || github.event.ref == 'refs/heads/main' 
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://git-action-demo-dev.surge.sh'
    steps:
      - name: get artifact
        uses: actions/download-artifact@v1
        with:
          name: simple-systems-artifect
      - name: deploy
        run: |
          npm install --global surge
          surge --project ./ --domain $DEVELOPMENT_DOMAIN --token ${{secrets.SURGE_TOKEN}}
        working-directory: simple-systems-artifect
            
  deploy-production:
    name: Deploy to Production
    if: github.event.ref == 'refs/heads/main' 
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://git-action-demo.surge.sh'
    steps:
      - name: get artifact
        uses: actions/download-artifact@v1
        with:
          name: simple-systems-artifect
      - name: deploy
        run: |
          npm install --global surge
          surge --project ./ --domain $PRODUCTION_DOMAIN --token ${{secrets.SURGE_TOKEN}}
        working-directory: simple-systems-artifect

  smoke-prod:
    name: smoke production
    if: github.event.ref == 'refs/heads/main'
    needs: [deploy-production]
    uses: bahmutov/cypress-workflows/.github/workflows/standard.yml@v1
          