name: CI CD Workflow

on: push

env:
  ARTIFACT_ID: simple-systems-artifect

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Branch name
        run: |
          echo running on branch ${GITHUB_REF##*/}
      
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      
      - name: Run the tests
        run: npm run test
      
      - name: build
        run: npm run build

      - name: Upload artifacts 
        uses: actions/upload-artifact@v3
        with:
          name: simple-systems-artifact
          path: build  
    
  deploy-feature:
    name: Deploy to feature branch
    if: |
      contains( github.ref, 'feature' ) || contains( github.ref, 'bugfix' ) 
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: get artifact
        uses: actions/download-artifact@v1
        with:
          name: $ARTIFACT_ID
      - name: deploy
        run: |
          npm install --global surge
          surge --project ./ --domain git-action-demo-${GITHUB_REF##*/}.surge.sh --token ${{secrets.SURGE_TOKEN}}
        working-directory: $ARTIFACT_ID
  
  deploy-staging:
    name: Deploy to staging
    if: |
      github.event.ref == 'refs/heads/develop' || github.event.ref == 'refs/heads/main' 
    needs: [build]
    runs-on: ubuntu-latest
    env: 
      DEVELOPMENT_DOMAIN: 'http://git-action-demo-dev.surge.sh'
    steps:
      - name: get artifact
        uses: actions/download-artifact@v1
        with:
          name: ${{ARTIFACT_ID}}
      - name: deploy
        run: |
          npm install --global surge
          surge --project ./ --domain $DEVELOPMENT_DOMAIN --token ${{secrets.SURGE_TOKEN}}
        working-directory: ${{ARTIFACT_ID}}
            
  deploy-production:
    name: Deploy to Production
    if: github.event.ref == 'refs/heads/main' 
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    env: 
      PRODUCTION_DOMAIN: 'http://git-action-demo.surge.sh'
    steps:
      - name: get artifact
        uses: actions/download-artifact@v1
        with:
          name: $ARTIFACT_ID
      - name: deploy
        run: |
          npm install --global surge
          surge --project ./ --domain $PRODUCTION_DOMAIN --token ${{secrets.SURGE_TOKEN}}
        working-directory: $ARTIFACT_ID

  smoke-production:
    name: Smoke production
    if: github.event.ref == 'refs/heads/main'
    needs: [deploy-production]
    uses: bahmutov/cypress-workflows/.github/workflows/standard.yml@v1
          