name: Branch Deleted

on: delete
jobs:
  delete:
    if: |
      contains( github.event.ref, 'feature' ) || contains( github.event.ref, 'bugfix' )
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          echo "Clean up for branch ${{ github.event.ref }}"
          npm install --global surge
          surge teardown git-action-demo-${github.event.ref}.surge.sh